#!/bin/bash

# backup-local-to-server
# SSHを用いて特定のディレクトリーを他のコンピューターに複製します。ユーザーは事前に複製先（サーバー）で「setup-ssh-server」を用いてSSHサーバーのホストを行い、複製元（クライアント）で「setup-ssh-local」を用いて公開鍵の生成と配布を行い、用途に応じてスクリプト内の定数、複製元、複製先を設定する必要があります。実行にはrsyncが必要です。

SSH_KEY_PATH="/home/${USER}/.ssh/${USER}/master-rsa"

echo "Connect to the server..."

read -p "Enter the address of the target server: " address

if [ -z "$address" ]; then
    echo "Put something in!"

    exit
fi

read -p "Enter the username of the target server (default is ${USER}): " username

if [ -z "$username" ]; then
    username="$USER"
fi

# ssh -i "$SSH_KEY_PATH" "${username}@${address}"

BACKUP_DIRECTORY_FROM="/home/${USER}"
BACKUP_DIRECTORY_TO="/home/${username}"
EXCLUDE_LIST="/home/${USER}/bin/backup-ignore.txt"

read -p "Are you sure you want to run \"${0##*/}\"? (Enter \"yes\" or anything else): " confirm

if [ "$confirm" != "yes" ]; then
    exit
fi

eval `ssh-agent`

ssh-add "$SSH_KEY_PATH"

function backupDirectoryLocalToServer {
    rsync -avPzh --delete --exclude-from="$EXCLUDE_LIST" \
        -e "ssh -i \"$SSH_KEY_PATH\"" \
        "$1" "${username}@${address}:${2}"
}

backupDirectoryLocalToServer \
    "${BACKUP_DIRECTORY_FROM}/bin" \
    "${BACKUP_DIRECTORY_TO}"
backupDirectoryLocalToServer \
    "${BACKUP_DIRECTORY_FROM}/init" \
    "${BACKUP_DIRECTORY_TO}"
backupDirectoryLocalToServer \
    "${BACKUP_DIRECTORY_FROM}/projects" \
    "${BACKUP_DIRECTORY_TO}"

ssh-agent -k
