#!/bin/bash

# backup-local-to-removable
# 特定のディレクトリーを暗号化されたデバイスに複製します。ユーザーは用途に応じてスクリプト内の定数、複製元、複製先を設定する必要があります。

DEVICE_NAME="backup"
DEVICE_MOUNT_POINT="/home/${USER}/backup"

BACKUP_DIRECTORY_FROM="/home/${USER}"
BACKUP_DIRECTORY_TO="$DEVICE_MOUNT_POINT"
EXCLUDE_LIST="/home/${USER}/bin/backup-ignore.txt"

if [ "$(df --output=target "$DEVICE_MOUNT_POINT" 2>/dev/null | tail -n +2)" != "$DEVICE_MOUNT_POINT" ]; then
    # ~/bin/mount-backup

    lsblk

    read -p "Enter the device name (/dev/*): " blockDeviceName

    if [ -z "$blockDeviceName" ]; then
        echo "Put something in!"

        exit
    fi

    blockDeviceName="/dev/$blockDeviceName"

    sudo cryptsetup open "$blockDeviceName" "$DEVICE_NAME"

    if [ $? != 0 ]; then
        echo "Failed to open the backup device."

        exit
    fi

    mkdir -p "$DEVICE_MOUNT_POINT"
    sudo mount "/dev/mapper/${DEVICE_NAME}" "$DEVICE_MOUNT_POINT"
fi

read -p "Are you sure you want to run \"${0##*/}\"? (Enter \"yes\" or anything else): " confirm

if [ "$confirm" != "yes" ]; then
    exit
fi

function backupDirectory {
    rsync -av --delete --exclude-from="$EXCLUDE_LIST" "$1" "$2"
}

backupDirectory \
    "${BACKUP_DIRECTORY_FROM}/bin" \
    "${BACKUP_DIRECTORY_TO}"
backupDirectory \
    "${BACKUP_DIRECTORY_FROM}/init" \
    "${BACKUP_DIRECTORY_TO}"
backupDirectory \
    "${BACKUP_DIRECTORY_FROM}/projects" \
    "${BACKUP_DIRECTORY_TO}"

# ~/bin/umount-backup

sudo umount "$DEVICE_MOUNT_POINT"
sudo cryptsetup close "$DEVICE_NAME"
