#!/bin/bash

# generate-random-files <size?> <num?> <format?> <target_directory?>
# ランダムなデータが書き込まれたファイルを生成します。

if [ -z "$1" ]; then
    size="1"
else
    size="$1"
fi

if [ -z "$2" ]; then
    num="1"
else
    num="$2"
fi

if [ -z "$3" ]; then
    format="%08d.bin"
else
    format="$3"
fi

if [ -d "$4" ]; then
    targetDirectory="${4%/}"
else
    targetDirectory="."
fi

for ((i=1; i<=$num; i++)); do
    dd \
        if=/dev/urandom \
        of="${targetDirectory}/$(printf "$format" "$i")" \
        bs=1M \
        count="$size" \
        status=none
done
