#!/bin/bash

# search-and-kill <name?>
# プロセスを検索・停止するための簡易的なスクリプトです。

if [ -z "$1" ]; then
    read -p "Enter the process name to search: " name
else
    name="$1"
fi

if [ -z "$name" ]; then
    echo "Put something in!"

    exit
fi

ps ax | grep "$name"

read -p "Enter the process ID to kill: " id

if [ -z "$id" ]; then
    echo "Put something in!"

    exit
fi

kill -9 $id
