#!/bin/bash

# setup-backup-device
# 暗号化されたデバイスを作成します。

DEVICE_NAME="backup"
DEVICE_MOUNT_POINT="/home/${USER}/backup"

echo "Create a backup device..."

lsblk

read -p "Enter the device name (/dev/*): " blockDeviceName

if [ -z "$blockDeviceName" ]; then
    echo "Put something in!"

    exit
fi

blockDeviceName="/dev/$blockDeviceName"

sudo parted "$blockDeviceName" --script mklabel gpt mkpart primary 0% 100% || exit
sudo cryptsetup luksFormat --type luks "$blockDeviceName"
sudo cryptsetup open "$blockDeviceName" "$DEVICE_NAME"
sudo mkfs.ext4 "/dev/mapper/${DEVICE_NAME}"

mkdir -p "$DEVICE_MOUNT_POINT"
sudo mount "/dev/mapper/${DEVICE_NAME}" "$DEVICE_MOUNT_POINT"
sudo chown "$USER" "$DEVICE_MOUNT_POINT"

sudo umount "$DEVICE_MOUNT_POINT"
sudo cryptsetup close "$DEVICE_NAME"
