#!/bin/bash

# shred-empty <mount_point?>
# ローカルディスクや外部メディア等の空領域を抹消します。

read -p "Are you sure you want to run \"${0##*/}\"? (Enter \"yes\" or anything else): " confirm

if [ "$confirm" != "yes" ]; then
    exit
fi

if [ ! -d "$1" ]; then
    target=""
else
    target="${1%/}"
fi

sudo dd \
    if=/dev/urandom \
    of="${target}/tempfile" \
    bs=1M \
    count=$(df -m --output=avail "${target}/" | tail -n +2) \
    status=progress && \
sudo rm -rf "${target}/tempfile"
