#!/bin/bash

# umount-cache
# 「mount-cache」で作成したフォルダーをアンマウント（抹消）します。

CACHE_DIRECTORY="/home/${USER}/cache"

read -p "Are you sure you want to run \"${0##*/}\"? (Enter \"yes\" or anything else): " confirm

if [ "$confirm" != "yes" ]; then
    exit
fi

sudo umount "$CACHE_DIRECTORY"
