#!/bin/bash

# umount-share
# 「mount-share」で作成したフォルダーをアンマウントします。

SHARE_DIRECTORY="/home/${USER}/share"

read -p "Are you sure you want to run \"${0##*/}\"? (Enter \"yes\" or anything else): " confirm

if [ "$confirm" != "yes" ]; then
    exit
fi

fusermount -u "$SHARE_DIRECTORY"
